### Get all movies
GET http://localhost:3000/movies

### Watchlist create route
POST http://localhost:3000/watchlist/create
Content-Type: application/json

{
    "name": "My Example Watchlist"
}

### Add movie to watchlist
POST http://localhost:3000/watchlist/add
Content-Type: application/json

{
    "watchlistId": "5faaae8f4845692ec168cec7",
    "movieId": "5faa6cc2f7f486baa5c56176"
}

### Get watchlists
GET http://localhost:3000/watchlist

### Get movies by watchlist id
GET http://localhost:3000/watchlist/5faaae8f4845692ec168cec7