### Get all movies
GET http://localhost:3000/movies

### Watchlist create route
POST http://localhost:3000/watchlist/create
Content-Type: application/json

{
    "name": "My Example Watchlist"
}

### Add movie to watchlist
POST http://localhost:3000/watchlist/add
Content-Type: application/json

{
    "watchlistId": "5faaa1f66acf38078bcf46f8",
    "movieId": "5faa6cc2f7f486baa5c56176"
}